# Generated by Django 6.0.3 on 2026-03-11 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repositories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_id', models.IntegerField()),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('merged', 'Merged')], default='open', max_length=20)),
                ('github_username', models.CharField(blank=True, max_length=100, null=True)),
                ('github_avatar', models.URLField(blank=True, null=True)),
                ('url', models.URLField()),
                ('base_branch', models.CharField(default='main', max_length=100)),
                ('head_branch', models.CharField(blank=True, max_length=100, null=True)),
                ('additions', models.IntegerField(default=0)),
                ('deletions', models.IntegerField(default=0)),
                ('changed_files', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('review_comments_count', models.IntegerField(default=0)),
                ('commits_count', models.IntegerField(default=0)),
                ('is_draft', models.BooleanField(default=False)),
                ('merged_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('github_created_at', models.DateTimeField(blank=True, null=True)),
                ('github_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pull_requests', to=settings.AUTH_USER_MODEL)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='repositories.repository')),
            ],
            options={
                'verbose_name': 'Pull Request',
                'verbose_name_plural': 'Pull Requests',
                'db_table': 'pull_requests',
                'ordering': ['-github_created_at'],
                'unique_together': {('repository', 'github_id')},
            },
        ),
    ]
