# Generated by Django 6.0.3 on 2026-03-11 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pullrequests', '0001_initial'),
        ('repositories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_issues', models.IntegerField(default=0)),
                ('critical_count', models.IntegerField(default=0)),
                ('warning_count', models.IntegerField(default=0)),
                ('info_count', models.IntegerField(default=0)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pull_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='pullrequests.pullrequest')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='repositories.repository')),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Code Review',
                'verbose_name_plural': 'Code Reviews',
                'db_table': 'code_reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info')], default='info', max_length=20)),
                ('category', models.CharField(choices=[('security', 'Security'), ('performance', 'Performance'), ('logic', 'Logic'), ('style', 'Style'), ('testing', 'Testing'), ('documentation', 'Documentation')], default='style', max_length=20)),
                ('file_name', models.CharField(blank=True, max_length=500, null=True)),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('code_snippet', models.TextField(blank=True, null=True)),
                ('suggestion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='reviews.codereview')),
            ],
            options={
                'verbose_name': 'Review Issue',
                'verbose_name_plural': 'Review Issues',
                'db_table': 'review_issues',
                'ordering': ['-severity', 'category'],
            },
        ),
    ]
