# Generated by Django 6.0.3 on 2026-03-11 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repositories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RepoScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scanning', 'Scanning'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('branch', models.CharField(default='main', max_length=100)),
                ('total_files_scanned', models.IntegerField(default=0)),
                ('total_issues', models.IntegerField(default=0)),
                ('critical_count', models.IntegerField(default=0)),
                ('warning_count', models.IntegerField(default=0)),
                ('info_count', models.IntegerField(default=0)),
                ('security_count', models.IntegerField(default=0)),
                ('performance_count', models.IntegerField(default=0)),
                ('quality_count', models.IntegerField(default=0)),
                ('dependency_count', models.IntegerField(default=0)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='repositories.repository')),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Repo Scan',
                'verbose_name_plural': 'Repo Scans',
                'db_table': 'repo_scans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info')], default='info', max_length=20)),
                ('category', models.CharField(choices=[('security', 'Security'), ('performance', 'Performance'), ('quality', 'Quality'), ('dependency', 'Dependency'), ('style', 'Style'), ('logic', 'Logic')], default='quality', max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('code_snippet', models.TextField(blank=True, null=True)),
                ('suggestion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='reposcanner.reposcan')),
            ],
            options={
                'verbose_name': 'Scan Issue',
                'verbose_name_plural': 'Scan Issues',
                'db_table': 'scan_issues',
                'ordering': ['severity', 'category'],
            },
        ),
    ]
